name: Update Downloads

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  check-repository:
    runs-on: ubuntu-latest
    outputs:
      is_dailyroutines: ${{ steps.check_repo.outputs.is_dailyroutines }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check Repository Info
      id: check_repo
      run: |
        repo_info=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }})
        owner=$(echo "$repo_info" | jq -r '.owner.login')
        name=$(echo "$repo_info" | jq -r '.name')
        if [[ "$owner" == "AtmoOmen1" && "$name" == "DailyRoutines" ]]; then
          echo "::set-output name=is_dailyroutines::true"
        else
          echo "::set-output name=is_dailyroutines::false"
        fi

  update-downloads:
    needs: check-repository
    if: needs.check-repository.outputs.is_dailyroutines == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Update total downloads
      run: |
        python update_downloads.py > downloads.txt
    - name: Commit and push if changed
      env:
        MY_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add downloads.txt
        git commit -m "Update Total Downloads" -a || echo "No changes to commit"
        git push --set-upstream https://${{ MY_PAT }}@github.com/${{ github.repository }} HEAD:main