name: Update Changelogs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Login to GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Get the latest non-pre release using GitHub CLI
        if: github.event_name == 'workflow_dispatch'
        run: |
          latest_release_body=$(gh release view --repo AtmoOmen/DailyRoutines --json body -q '.body')
          latest_release_time=$(gh release view --repo AtmoOmen/DailyRoutines --json publishedAt -q '.publishedAt' | cut -c 1-10 | sed 's/-/\//g')
          echo "LATEST_RELEASE_BODY=\"$latest_release_body\"" >> $GITHUB_ENV
          echo "LATEST_RELEASE_TIME=\"$latest_release_time\"" >> $GITHUB_ENV

      - name: Write release content to Changelog.txt
        run: |
          mkdir -p Assets
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "${{ github.event.body }}" > Assets/Changelog.txt
            echo "$(date -d "${{ github.event.release.published_at }}" '+%Y/%m/%d')" > Assets/ChangelogTime.txt
          else
            echo "$LATEST_RELEASE_BODY" > Assets/Changelog.txt
            echo "$LATEST_RELEASE_TIME" > Assets/ChangelogTime.txt
          fi

      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add Assets/Changelog.txt
          git add Assets/ChangelogTime.txt
          git commit -m "Update Changelog and Time"
          git push
